name: 'cms_synthetic_connector'
version: '0.1'
config-version: 2

profile: default

vars:

  claims_enabled: true
  clinical_enabled: false

  ## CMS HCC data mart vars
  # Setting the payment year to year needed for the demo data
  cms_hcc_payment_year: 2023

  ## Quality Measure data mart vars
  # Setting the reporting period to date needed for demo data
  quality_measures_period_end: "2023-12-31"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  cms_synthetic_connector:
    beneficiary:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','beneficiary.csv', compression=true, null_marker=true) }}"
    carrier:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','carrier.csv', compression=true, null_marker=true) }}"
    dme:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','dme.csv', compression=true, null_marker=true) }}"
    hha:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','hha.csv', compression=true, null_marker=true) }}"
    hospice:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','hospice.csv', compression=true, null_marker=true) }}"
    inpatient:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','inpatient.csv', compression=true, null_marker=true) }}"
    outpatient:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','outpatient.csv', compression=true, null_marker=true) }}"
    pde:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','pde.csv', compression=true, null_marker=true) }}"
    snf:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/cms-synthetic','snf.csv', compression=true, null_marker=true) }}"



