name: 'cms_synthetic_connector'
version: '0.1.7'
config-version: 2

profile: default

vars:

  claims_enabled: true
  clinical_enabled: false
  input_database: cms_synthetic
  input_schema: raw

  ## CMS HCC data mart vars
  # Setting the payment year to year needed for the demo data
  cms_hcc_payment_year: 2023

  ## Quality Measure data mart vars
  # Setting the reporting period to date needed for demo data
  quality_measures_period_end: "2023-12-31"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"



