default:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account
      keyfile: ./creds.json
      project: dev-ci-testing
      dataset: connector
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
