default:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('TUVA_BIGQUERY_PROJECT') }}"
      keyfile: "{{ env_var('TUVA_BIGQUERY_TOKEN') }}"
      dataset: connector
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
